// GENERATED by tools/build_vega_theme.py - do not edit by hand.
// NCDPI light-mode palette arrays sourced from the brand color CSV.
export const NCDPI = {
  "groups": {
    "2": [
      "#5085BC",
      "#FF9015"
    ],
    "3": [
      "#5085BC",
      "#FF9015",
      "#922880"
    ],
    "4": [
      "#5085BC",
      "#FF9015",
      "#922880",
      "#3D803F"
    ],
    "5": [
      "#5085BC",
      "#FF9015",
      "#922880",
      "#3D803F",
      "#D3B10B"
    ],
    "6": [
      "#5085BC",
      "#FF9015",
      "#922880",
      "#3D803F",
      "#D3B10B",
      "#BE7EB3"
    ]
  },
  "groupsTotal": "#003A70",
  "diverging": {
    "3": [
      "#B33A12",
      "#DEDEDE",
      "#077890"
    ],
    "5": [
      "#B33A12",
      "#C88C78",
      "#DEDEDE",
      "#86A4AE",
      "#077890"
    ],
    "7": [
      "#B33A12",
      "#C26F54",
      "#D1BCB5",
      "#DEDEDE",
      "#B9C4C7",
      "#6593A1",
      "#077890"
    ],
    "9": [
      "#B33A12",
      "#BE6143",
      "#CC9F91",
      "#D5CBC8",
      "#DEDEDE",
      "#CACFD1",
      "#9AB0B7",
      "#548B9C",
      "#077890"
    ]
  },
  "divergingContinuous": {
    "begin": "#B33A12",
    "end": "#077890",
    "mid": "#DEDEDE"
  },
  "seqGood": {
    "2": [
      "#8BAEB9",
      "#077890"
    ],
    "3": [
      "#A9BEC6",
      "#6D9CAC",
      "#077890"
    ],
    "4": [
      "#B6C6CC",
      "#8BAEB9",
      "#5C93A6",
      "#077890"
    ],
    "5": [
      "#BECBCF",
      "#9DB8C1",
      "#7AA3B1",
      "#508EA2",
      "#077890"
    ]
  },
  "seqGoodContinuous": {
    "begin": "#DEDEDE",
    "end": "#077890"
  },
  "seqBad": {
    "2": [
      "#DC8F76",
      "#B33A12"
    ],
    "3": [
      "#E2A996",
      "#D37355",
      "#B33A12"
    ],
    "4": [
      "#E3B6A8",
      "#DC8F76",
      "#CD6544",
      "#B33A12"
    ],
    "5": [
      "#E4BEB2",
      "#E09F89",
      "#D77F62",
      "#C85D3A",
      "#B33A12"
    ]
  },
  "seqBadContinuous": {
    "begin": "#DEDEDE",
    "end": "#B33A12"
  },
  "seqNeutral": {
    "2": [
      "#9CB0CD",
      "#5085BC"
    ],
    "3": [
      "#B2BFD3",
      "#85A2C8",
      "#5085BC"
    ],
    "4": [
      "#BDC7D6",
      "#9CB0CD",
      "#799AC5",
      "#5085BC"
    ],
    "5": [
      "#C4CBD7",
      "#A9B9D1",
      "#8EA7CA",
      "#7196C3",
      "#5085BC"
    ]
  },
  "seqNeutralContinuous": {
    "begin": "#DEDEDE",
    "end": "#5085BC"
  },
  "highlight": {
    "neutral": "#B7B9BB",
    "focus": "#003A70",
    "best": "#077890",
    "worst": "#B33A12"
  },
  "elements": {
    "axisRuler": "#DEDEDE",
    "divider": "#DEDEDE",
    "gridline": "#DEDEDE",
    "referenceLine": "#003A70"
  },
  "text": {
    "annotation": "#842175",
    "axisLabel": "#000000",
    "axisValue": "#525A60",
    "note": "#525A60",
    "subtitle": "#525A60",
    "title": "#000000",
    "dataLabel": "#000000"
  },
  "background": "#FFFFFF",
  "spgGrade": {
    "F": "#B33A12",
    "D": "#C88C78",
    "C": "#DEDEDE",
    "B": "#86A4AE",
    "A": "#077890"
  }
};
export default NCDPI;
